name: Deploy to SRV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up SSH to authenticate to the server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      # Log in to Docker Hub (or GitHub Container Registry, or any container registry you're using)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Build application image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/mc-dash:latest -f Dockerfile .


      - name: Push application image
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}"/mc-dash:latest
          

      # SSH into VPS and pull the latest Docker image, stop old container, and start the new one
      - name: Deploy container to SRV
        run: |
          ssh ${{ secrets.SRV_USER }}@${{ secrets.SRV }} << 'EOF'
      
            docker pull "${{ secrets.DOCKER_USERNAME }}"/mc-dash:latest

            docker stop mc_dash_container || true
            docker rm mc_dash_container || true

            ${{ secrets.DOCKER_CMD }}
          EOF